import { randomUUID } from 'node:crypto';
import type { FastifyInstance } from 'fastify';
import type { Pool } from 'pg';
import { z } from 'zod';
import { snapshotDigest } from './digest.js';
import { canDecideApproval, canReadEvidence, canWriteEvidence } from './authorization.js';
import { modeEnvelope, modeError } from '../http.js';
import { insertAuditEvent } from '../prime/audit.js';

const confidence = z.number().min(0).max(1).optional();
const documentSchema = z.object({ materialBatchId: z.string().uuid().optional(), originalFilename: z.string().min(1), mediaType: z.string().optional(), sourceType: z.enum(['USER_UPLOAD','ERP_EXPORT','SUPPLIER_DECLARATION','THIRD_PARTY_CERTIFICATE','SENSOR_MEASUREMENT','MANUAL_ENTRY','SYSTEM_GENERATED']), storageStatus: z.enum(['METADATA_ONLY','PENDING_UPLOAD','AVAILABLE','UNAVAILABLE']), contentDigestSha256: z.string().regex(/^[a-f0-9]{64}$/i).optional(), sourceUri: z.string().optional(), issuedAt: z.string().datetime().optional(), expiresAt: z.string().datetime().optional() });
const recordSchema = z.object({ documentId: z.string().uuid().optional(), materialBatchId: z.string().uuid().optional(), fieldName: z.string().min(1), value: z.unknown(), unit: z.string().optional(), extractionMethod: z.enum(['MANUAL','SYSTEM_RULE','FUTURE_AI_DRAFT','IMPORT']), extractionVersion: z.string().min(1), confidence, sourceLocator: z.string().optional() });
const claimSchema = z.object({ materialBatchId: z.string().uuid().optional(), claimType: z.enum(['MATERIAL_COMPOSITION','RECYCLED_CONTENT','MATERIAL_QUANTITY','EMISSION_ACTIVITY','EMISSION_CALCULATION','CIRCULARITY_OUTCOME','RECYCLER_CAPABILITY','SUPPLIER_DECLARATION','OTHER']), statement: z.string().min(1), value: z.unknown(), unit: z.string().optional(), calculationMethod: z.string().optional(), calculationVersion: z.string().optional(), emissionFactorReference: z.string().optional(), confidence, uncertaintyNote: z.string().optional() });
const approvalSchema = z.object({ claimId: z.string().uuid().optional(), sessionId: z.string().uuid().optional(), requestType: z.enum(['CLAIM_VERIFICATION','CLAIM_REJECTION','EVIDENCE_REVIEW','HIGH_IMPACT_WORKFLOW']), requiredRoles: z.array(z.enum(['OWNER','ESG_LEAD','OPERATIONS','REVIEWER','VIEWER'])).min(1), expiresAt: z.string().datetime().optional(), reason: z.string().optional() }).refine((value) => Boolean(value.claimId) !== Boolean(value.sessionId), 'exactly one claimId or sessionId is required');
const decisionSchema = z.object({ decision: z.enum(['APPROVED','REJECTED']), comment: z.string().optional() });
const linkSchema=z.object({evidenceRecordId:z.string().uuid().optional(),evidenceDocumentId:z.string().uuid().optional(),relationType:z.enum(['SUPPORTS','CONTRADICTS','CALCULATION_INPUT','REVIEW_REFERENCE']),required:z.boolean().default(true)}).refine(value=>Boolean(value.evidenceRecordId)!==Boolean(value.evidenceDocumentId),'exactly one evidence link is required');

export function registerEvidenceRoutes(app: FastifyInstance, pool: Pool): void {
  const error = (request: Parameters<FastifyInstance['get']>[1] extends infer T ? never : never, code: string, message: string) => void request;
  app.post('/v1/evidence-documents', async (request, reply) => {
    try { canWriteEvidence(request.earthTenant); } catch { return reply.status(403).send(modeError(request.server.earthAuthMode, 'FORBIDDEN', 'You do not have permission to perform this action.', { correlationId: request.id })); }
    const input = documentSchema.safeParse(request.body); if (!input.success) return reply.status(400).send(modeError(request.server.earthAuthMode, 'VALIDATION_ERROR', 'Invalid evidence document.', { correlationId: request.id }));
    const id = randomUUID(); const value = input.data;
    await pool.query(`INSERT INTO evidence_documents (id,organization_id,material_batch_id,original_filename,media_type,source_type,storage_status,content_digest_sha256,source_uri,issued_at,expires_at,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)`, [id, request.earthTenant.organizationId, value.materialBatchId ?? null, value.originalFilename, value.mediaType ?? null, value.sourceType, value.storageStatus, value.contentDigestSha256 ?? null, value.sourceUri ?? null, value.issuedAt ?? null, value.expiresAt ?? null, request.earthTenant.actorId]);
    await audit(pool, request, 'EVIDENCE_DOCUMENT_CREATED', id, value); return reply.status(201).send(modeEnvelope(request.server.earthAuthMode, { document: { id, ...value }, verificationStatus: 'INPUT_UNVERIFIED', limitation: 'Metadata only; not verified evidence.' }));
  });
  app.post('/v1/evidence-records', async (request, reply) => {
    try { canWriteEvidence(request.earthTenant); } catch { return reply.status(403).send(modeError(request.server.earthAuthMode, 'FORBIDDEN', 'You do not have permission to perform this action.', { correlationId: request.id })); }
    const input = recordSchema.safeParse(request.body); if (!input.success) return reply.status(400).send(modeError(request.server.earthAuthMode, 'VALIDATION_ERROR', 'Invalid evidence record.', { correlationId: request.id }));
    const id=randomUUID(), value=input.data; const status=value.extractionMethod==='FUTURE_AI_DRAFT'?'INPUT_UNVERIFIED':'INPUT_UNVERIFIED';
    await pool.query(`INSERT INTO evidence_records (id,organization_id,document_id,material_batch_id,field_name,value_json,unit,extraction_method,extraction_version,confidence,verification_status,source_locator,created_by) VALUES ($1,$2,$3,$4,$5,$6::jsonb,$7,$8,$9,$10,$11,$12,$13)`,[id,request.earthTenant.organizationId,value.documentId??null,value.materialBatchId??null,value.fieldName,JSON.stringify(value.value),value.unit??null,value.extractionMethod,value.extractionVersion,value.confidence??null,status,value.sourceLocator??null,request.earthTenant.actorId]);
    await audit(pool,request,'EVIDENCE_RECORD_CREATED',id,value); return reply.status(201).send(modeEnvelope(request.server.earthAuthMode,{record:{id,...value,verificationStatus:status}}));
  });
  app.post('/v1/claims', async (request, reply) => {
    try { canWriteEvidence(request.earthTenant); } catch { return reply.status(403).send(modeError(request.server.earthAuthMode, 'FORBIDDEN', 'You do not have permission to perform this action.', { correlationId: request.id })); }
    const input=claimSchema.safeParse(request.body); if(!input.success)return reply.status(400).send(modeError(request.server.earthAuthMode,'VALIDATION_ERROR','Invalid claim.',{correlationId:request.id}));
    const id=randomUUID(),value=input.data; await pool.query(`INSERT INTO claims (id,organization_id,material_batch_id,claim_type,statement,value_json,unit,calculation_method,calculation_version,emission_factor_reference,confidence,uncertainty_note,status,created_by) VALUES ($1,$2,$3,$4,$5,$6::jsonb,$7,$8,$9,$10,$11,$12,'DRAFT',$13)`,[id,request.earthTenant.organizationId,value.materialBatchId??null,value.claimType,value.statement,JSON.stringify(value.value),value.unit??null,value.calculationMethod??null,value.calculationVersion??null,value.emissionFactorReference??null,value.confidence??null,value.uncertaintyNote??null,request.earthTenant.actorId]);
    await audit(pool,request,'CLAIM_CREATED',id,value); return reply.status(201).send(modeEnvelope(request.server.earthAuthMode,{claim:{id,...value,status:'DRAFT'}}));
  });
  app.post('/v1/claims/:claimId/evidence',async(request,reply)=>{try{canWriteEvidence(request.earthTenant);}catch{return reply.status(403).send(err(request,'FORBIDDEN','You do not have permission to perform this action.'));}const input=linkSchema.safeParse(request.body);if(!input.success)return reply.status(400).send(err(request,'INVALID_EVIDENCE_LINK','Invalid evidence link.'));const claimId=(request.params as {claimId:string}).claimId;const claim=await pool.query(`SELECT 1 FROM claims WHERE id=$1 AND organization_id=$2`,[claimId,request.earthTenant.organizationId]);if(!claim.rows[0])return reply.status(404).send(err(request,'CLAIM_NOT_FOUND','Resource not found.'));const value=input.data;const table=value.evidenceRecordId?'evidence_records':'evidence_documents';const evidenceId=value.evidenceRecordId??value.evidenceDocumentId;const evidence=await pool.query(`SELECT 1 FROM ${table} WHERE id=$1 AND organization_id=$2`,[evidenceId,request.earthTenant.organizationId]);if(!evidence.rows[0])return reply.status(404).send(err(request,'INVALID_EVIDENCE_LINK','Resource not found.'));const id=randomUUID();await pool.query(`INSERT INTO claim_evidence (id,organization_id,claim_id,evidence_record_id,evidence_document_id,relation_type,required) VALUES ($1,$2,$3,$4,$5,$6,$7)`,[id,request.earthTenant.organizationId,claimId,value.evidenceRecordId??null,value.evidenceDocumentId??null,value.relationType,value.required]);await audit(pool,request,'CLAIM_EVIDENCE_LINKED',id,value);return reply.status(201).send(modeEnvelope(request.server.earthAuthMode,{link:{id,claimId,...value}}));});
  app.get('/v1/claims/:claimId', async (request, reply) => { try { canReadEvidence(request.earthTenant); } catch { return reply.status(403).send(modeError(request.server.earthAuthMode,'FORBIDDEN','You do not have permission to perform this action.',{correlationId:request.id})); } const row=await pool.query(`SELECT * FROM claims WHERE id=$1 AND organization_id=$2`,[(request.params as {claimId:string}).claimId,request.earthTenant.organizationId]); if(!row.rows[0])return reply.status(404).send(modeError(request.server.earthAuthMode,'CLAIM_NOT_FOUND','Resource not found.',{correlationId:request.id})); return reply.send(modeEnvelope(request.server.earthAuthMode,{claim:row.rows[0]})); });
  app.post('/v1/approval-requests', async (request, reply) => {
    try { canWriteEvidence(request.earthTenant); } catch { return reply.status(403).send(err(request,'FORBIDDEN','You do not have permission to perform this action.')); }
    const input=approvalSchema.safeParse(request.body); if(!input.success)return reply.status(400).send(err(request,'VALIDATION_ERROR','Invalid approval request.'));
    const value=input.data; const snapshot=await approvalSnapshot(pool,request.earthTenant.organizationId,value.claimId); if(!snapshot)return reply.status(404).send(err(request,'CLAIM_NOT_FOUND','Resource not found.'));
    const id=randomUUID(); await pool.query(`INSERT INTO approval_requests (id,organization_id,claim_id,session_id,request_type,state,requested_by,expires_at,required_roles,evidence_snapshot_digest_sha256,claim_snapshot_digest_sha256,reason) VALUES ($1,$2,$3,$4,$5,'PENDING',$6,$7,$8,$9,$10,$11)`,[id,request.earthTenant.organizationId,value.claimId??null,value.sessionId??null,value.requestType,request.earthTenant.actorId,value.expiresAt??null,value.requiredRoles,snapshot.evidence,snapshot.claim,value.reason??null]);
    await audit(pool,request,'APPROVAL_REQUEST_CREATED',id,{...value,snapshot}); return reply.status(201).send(modeEnvelope(request.server.earthAuthMode,{request:{id,state:'PENDING',...value,evidenceSnapshotDigestSha256:snapshot.evidence,claimSnapshotDigestSha256:snapshot.claim},limitation:'Human review request; not automated verification.'}));
  });
  app.post('/v1/approval-requests/:requestId/decision', async (request, reply) => {
    const input=decisionSchema.safeParse(request.body); if(!input.success)return reply.status(400).send(err(request,'VALIDATION_ERROR','Invalid approval decision.'));
    const found=await pool.query(`SELECT * FROM approval_requests WHERE id=$1 AND organization_id=$2`,[(request.params as {requestId:string}).requestId,request.earthTenant.organizationId]); const approval=found.rows[0]; if(!approval)return reply.status(404).send(err(request,'APPROVAL_REQUEST_NOT_FOUND','Resource not found.'));
    try { canDecideApproval(request.earthTenant,approval.required_roles); } catch { await audit(pool,request,'APPROVAL_ROLE_BLOCKED',approval.id,{}); return reply.status(403).send(err(request,'APPROVAL_ROLE_REQUIRED','You do not have the required approval role.')); }
    if(approval.requested_by===request.earthTenant.actorId)return reply.status(403).send(err(request,'APPROVAL_SELF_REVIEW_FORBIDDEN','Request creators cannot approve their own request.'));
    if(approval.state!=='PENDING')return reply.status(409).send(err(request,'APPROVAL_REQUEST_NOT_PENDING','Approval request is not pending.'));
    if(approval.expires_at&&new Date(approval.expires_at)<new Date())return reply.status(409).send(err(request,'APPROVAL_REQUEST_EXPIRED','Approval request has expired.'));
    const snapshot=await approvalSnapshot(pool,request.earthTenant.organizationId,approval.claim_id); if(!snapshot||snapshot.evidence!==approval.evidence_snapshot_digest_sha256||snapshot.claim!==approval.claim_snapshot_digest_sha256){await audit(pool,request,'APPROVAL_SNAPSHOT_STALE',approval.id,{});return reply.status(409).send(err(request,'APPROVAL_SNAPSHOT_STALE','Approval snapshot is stale.'));}
    const claim=approval.claim_id?(await pool.query(`SELECT created_by FROM claims WHERE id=$1 AND organization_id=$2`,[approval.claim_id,request.earthTenant.organizationId])).rows[0]:null; if(claim?.created_by===request.earthTenant.actorId)return reply.status(403).send(err(request,'APPROVAL_SELF_REVIEW_FORBIDDEN','Claim creators cannot approve their own claim.'));
    if(input.data.decision==='APPROVED'&&approval.request_type==='CLAIM_VERIFICATION'){const required=await pool.query(`SELECT 1 FROM claim_evidence WHERE claim_id=$1 AND organization_id=$2 AND required=true`,[approval.claim_id,request.earthTenant.organizationId]);if(!required.rows[0])return reply.status(409).send(err(request,'REQUIRED_EVIDENCE_MISSING','Required evidence is missing.'));}
    const client=await pool.connect();try{await client.query('BEGIN');await client.query(`INSERT INTO approval_decisions (id,organization_id,approval_request_id,decision,decided_by,comment,evidence_snapshot_digest_sha256,claim_snapshot_digest_sha256,auth_mode,correlation_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[randomUUID(),request.earthTenant.organizationId,approval.id,input.data.decision,request.earthTenant.actorId,input.data.comment??null,approval.evidence_snapshot_digest_sha256,approval.claim_snapshot_digest_sha256,request.earthTenant.authMode,request.earthTenant.correlationId]);await client.query(`UPDATE approval_requests SET state=$2,updated_at=now() WHERE id=$1`,[approval.id,input.data.decision]);if(approval.claim_id&&approval.request_type==='CLAIM_VERIFICATION')await client.query(`UPDATE claims SET status=$2,updated_at=now() WHERE id=$1 AND organization_id=$3`,[approval.claim_id,input.data.decision==='APPROVED'?'VERIFIED':'REJECTED',request.earthTenant.organizationId]);await client.query('COMMIT');}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}
    await audit(pool,request,`APPROVAL_${input.data.decision}`,approval.id,input.data); return reply.send(modeEnvelope(request.server.earthAuthMode,{requestId:approval.id,state:input.data.decision,decision:input.data.decision}));
  });
}

function err(request:any,code:string,message:string){return modeError(request.server.earthAuthMode,code,message,{correlationId:request.id});}
async function approvalSnapshot(pool:Pool,org:string,claimId?:string){if(!claimId)return {evidence:snapshotDigest({organizationId:org,evidence:[]}),claim:null};const claim=(await pool.query(`SELECT * FROM claims WHERE id=$1 AND organization_id=$2`,[claimId,org])).rows[0];if(!claim)return null;const evidence=(await pool.query(`SELECT ce.relation_type,ce.required,er.id AS record_id,er.value_json,ed.id AS document_id,ed.content_digest_sha256 FROM claim_evidence ce LEFT JOIN evidence_records er ON er.id=ce.evidence_record_id LEFT JOIN evidence_documents ed ON ed.id=ce.evidence_document_id WHERE ce.claim_id=$1 AND ce.organization_id=$2 ORDER BY ce.id`,[claimId,org])).rows;return {evidence:snapshotDigest({organizationId:org,evidence}),claim:snapshotDigest({organizationId:org,claim})};}

async function audit(pool: Pool, request: any, eventType: string, resourceId: string, input: unknown): Promise<void> { const client=await pool.connect(); try { await insertAuditEvent(client,{organizationId:request.earthTenant.organizationId,actorType:'USER',actorId:request.earthTenant.actorId,authMode:request.earthTenant.authMode,correlationId:request.earthTenant.correlationId,eventType,input,metadata:{resourceId}}); } finally { client.release(); } }